TutteInstitute/vectorizers

vectorizers/_vectorizers.py, vectorizers/distances.py
Type checking for DistributionVectorizer
=> Type checking for DistributionVectorizer

.circleci/config.yml, .travis.yml, vectorizers/_vectorizers.py, vectorizers/tests/test_common.py
Add very minimal tests (we can add such things for more vectorizers as well). Fix the NgramVectorizer.
=> Add some very basic tests. Pass the tests.

.travis.yml, README.rst, appveyor.yml
Just fixing up stuff in the test config.
=> Test infrastructure/config fixes

vectorizers/_vectorizers.py, vectorizers/tests/test_common.py, vectorizers/tests/test_distances.py
Started testing most of the vectorizers at a very basic level. Began a testing module for the distances. I would welcome help writing extra tests for those.
=> Add more tests; start testing distances

vectorizers/_vectorizers.py, vectorizers/optimal_transport.py, vectorizers/tests/test_common.py
A downside here is that my optimal transport work got mixed into this because I didn't have a side branch for it. Sorry. Just ignore that file for now.
=> Handle 1-grams differently

vectorizers/_vectorizers.py, vectorizers/optimal_transport.py, vectorizers/tests/test_common.py
This includes all the optimal_transport stuff. It is still technically a WIP, but we may as well get it in there for now.
=> Support filtering tokens by regex pattern

vectorizers/_vectorizers.py
Rename column dictionaries to common naming schemes and rerun black on everything (it changed some string quoting).
=> Rename dictionaries to common naming scheme

vectorizers/_vectorizers.py, vectorizers/tests/test_common.py
Folded Colin's new changes into my code, blackened and added a .transform to TokenCooccurrenceVectorizer along with some unit testing.
=> TokenCooccurrenceVectorizer.transform()

vectorizers/_vectorizers.py
Add a check that the model is fitted before running transform.
=> Check fitted before transform

.travis.yml, README.rst
Add coveralls integration and separate out coverage run from non-coverage run.
=> Add coveralls integration 

vectorizers/_vectorizers.py, vectorizers/tests/test_common.py
Basic function for node removal; should work in general cases.
=> Remove a node from a DAG for use in LabelledGraphCooccurrenceVectorizer

vectorizers/_vectorizers.py, vectorizers/tests/test_common.py, vectorizers/utils.py
I also did this for LabelledTrees and added a transform function to it.
=> Added min/max doc frequency/occurrences

vectorizers/_vectorizers.py, vectorizers/tests/test_common.py
Hopefully this will ensure self loops do not cause unexpected issues.
=> Handle self-loops in node removal

vectorizers/distances.py, vectorizers/optimal_transport.py
You have to create a custom ground metric that is a closure over the ground_vectors. I added a function to do that for you.
=> Add a sparse Kantorovich distance

vectorizers/_vectorizers.py, vectorizers/tests/test_common.py
It’s for both the Labelled Trees and Token Cooccurrence vectorizers.
=> Added a masking token for pruned vocabulary 

vectorizers/_vectorizers.py, vectorizers/_window_kernels.py, vectorizers/tests/test_common.py
added token frequency to the kernel functions
=> added token frequency to the kernel functions

vectorizers/_vectorizers.py, vectorizers/_window_kernels.py, vectorizers/tests/test_common.py, vectorizers/utils.py
Added the ability to pass kernel and window args in (together with new window and kernel function and a couple tests)
=> Kernel and Window args

vectorizers/_vectorizers.py, vectorizers/_window_kernels.py, vectorizers/em_token_cooccurrence.py, vectorizers/tests/test_common.py
Added kernel offset to zero out the first few terms if needed (to handle non-adjacent kernels) and updated the directional matrices to transpose only under fixed windowing.
=> Kernel offsets

vectorizers/_vectorizers.py, vectorizers/_window_kernels.py, vectorizers/em_token_cooccurrence.py, vectorizers/linear_optimal_transport.py, vectorizers/tests/test_common.py, vectorizers/utils.py
Added skip_grams to EM TCV and moved str_to_bytes to the utils.... and my Black undid some of the changes that Leland had done for some reason to a couple files; not many but a few.
=> EMTCV skip_grams

vectorizers/em_token_cooccurrence.py, vectorizers/tests/test_transformers.py, vectorizers/transformers.py
This adds simple versions of the information weight transformer and the remove effects transformer. I would like to, at some point, rename the remove effects transformer but now is not that time.
=> Add simple transformers

vectorizers/utils.py
Check if we have numba enabled; if not create a suitable pure python function
=> Handle disabling JIT for to_fixed_tuple

vectorizers/coo_utils.py, vectorizers/tests/test_common.py, vectorizers/token_cooccurrence_vectorizer.py, vectorizers/utils.py
This includes document context EM, document context token masking, and the ability to normalize windows via L_1 or Bayesian normalization.
=> Document_context EM

vectorizers/tests/test_common.py, vectorizers/token_cooccurrence_vectorizer.py, vectorizers/utils.py
Added a summarize_embedding function to vectorizers.utils.  This should be handy for building a generic label for a row of our vectorizers library based on the k most frequent column names.
=> Added a summarize_embedding function to vectorizers.utils.

doc/CategoricalColumnTransfomer_documentation.ipynb
I added a notebook documenting using the CategoricalColumnTransformer on some Health Canada adverse drug effects reporting data.
=> CategoricalColumnTransformer documentation

.circleci/config.yml, .travis.yml, appveyor.yml, requirements.txt, setup.py, vectorizers/linear_optimal_transport.py, vectorizers/token_cooccurrence_vectorizer.py
Add dask to requirements and test infrastructure; then use dask for simple parallelism in constructing the cooccurrence matrix. This is not a full distributed version of things, but it is a start, and speeds things up with reasonable parallel computation.
=> Add dask for simple parallel computation in the word vectorizer

README.rst, vectorizers/transformers.py
I'm still tweaking the params/options for info weight transformers. I think this should get things to a flexible enough state to support various use cases.
I have also updated the README. It still needs work, but this is a more complete skeleton.
=> Make some changes to how info weight works; New README.

vectorizers/tests/test_transformers.py, vectorizers/transformers.py
This is essentially just a Taken's embedding, but gives it tools to work with classical time-series data. I tried to have a reasonable range of options/flexibility in how you sample windows, but would welcome any suggestions for further options. In principle it might be possible to "learn" good window parameters from the input data (right now fit does nothing beyond verifying parameters) but I don't quite know what the right way to do that would be exactly.
=> SlidingWindowTransformer for working with time-series like data

appveyor.yml, requirements.txt, vectorizers/__init__.py, vectorizers/distribution_vectorizer.py, vectorizers/mixed_gram_vectorizer.py, vectorizers/tests/test_common.py
Add Lempel-Ziv and Byte Pair Encodign based vectorizers allowing for vectorization of non-tokenized strings.
Also includes a basic outline of a distribution vectorizer, but this may require something more powerful than pomegranate.
=> Add Compression Vectorizers

vectorizers/__init__.py, vectorizers/_vectorizers.py, vectorizers/edge_list_vectorizer.py, vectorizers/tests/test_edge_list_vectorizer.py
Added a new class for vectorizing data in the form of row_name, column_name, count triples.  
Added some unit tests.
Documentation and an expanded functionality to come at a later date.
=> added EdgeListVectorizer

vectorizers/tests/test_transformers.py
This checks whether invoking fit() and transform() in turn yield the same result as fit_transform().
=> Add unit test for CFC transformer

doc/categorical_column_transformer_example.ipynb
heading level typo in a notebook
=> Fixed categorical column transformer example in our documentation 

doc/api.rst, doc/conf.py, doc/index.rst, doc/quick_start.rst
Fix up some of the documentation structures; remove unnecessary templates etc.
=> Some documentation cleanup

README.rst
The LICENSE file uses the 3-clause license. Updating the README to reflect that.
=> [Typo] Update README.rst

vectorizers/mixed_gram_vectorizer.py, vectorizers/tests/__init__.py, vectorizers/tests/test_bpe.py, vectorizers/tests/test_common.py
- More tests
- Setting of max_char_code as a parameter
- Parallel encoding on `.tranform()`
=> Improvements to byte pair encoding vectorizer
